---

- name: EPEL | Repositorio
  yum:
    name: epel-release
    enablerep: "{{ item.repo }}"
    state: latest
  with_items:
    - { repo: 'epel' }
    - { repo: 'epel-source' }

- name: PACKAGE | Paquetes esenciales 
  yum:
    name:
      - vim
      - htop
      - bind-utils
      - colordiff
      - curl
      - wget
      - mtr
      - tcpdump
      - tree
      - zip
      - unzip
  state: latest

- name: VIM | Archivo de conf
  copy: 
    src: vim_config
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0644 

- name: SHELL | Añadiendo color al prompt de root
  lineinfile:
   path: /root/.bashrc
   line: 'export PS1="\[\e[36m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[36m\]@\[\e[m\]\[\e[31m\]\h\[\e[m\]\[\e[36m\]:\[\e[m\]\[\e[31m\]\w\[\e[m\]\[\e[36m\]]\[\e[m\]\[\e[31m\]:\[\e[m\] " '
