---

- hosts: whm
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Installing EPEL repository
      yum: 
        name: epel-release
        state: latest

    - name: Installing Python package
      yum: 
        name: python2-pip
        state: latest

    - name: Installing with PIP
      pip:
        name: awscli
        extra_args: --upgrade
         
    - name: Fixing AWS permissions
      shell: 'chmod 755 /bin/aws*'

    - name: AWS credentials files
      copy: src=./.aws dest=/root/ mode=0640 
