---

- name: PIP | Installation package
  yum:
    name: python2-pip
    state: latest

- name: AWSCLI | Instalation via PIP
  pip:
    name: awscli
    extra_args: --upgrade

- name: PERMISSION | AWSCLI permission
  shell: |
    /bin/find /bin/ -type f -name 'aws' -o -name 'aws_compl*' | /bin/xargs chmod 0750

- name: FOLDER | AWS access
  file:
    path: /root/.aws
    state: directory
    owner: root
    group: root
    mode: 755

- name: CREDENTIALS | AWS credentials file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'config.j2', dest: '/root/.aws/config' }
    - { src: 'credentials.j2', dest: '/root/.aws/credentials' }
