---

- name: Package installation
  yum:
    name:
      - perl-Switch
      - perl-DateTime
      - perl-Sys-Syslog
      - perl-LWP-Protocol-https
      - perl-Digest-SHA
      - zip
      - unzip
    state: latest

- name: GET | aws package
  get_url:
    url: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip
    dest: /opt/CloudWatchMonitoringScripts-1.2.1.zip

- name: UNZIP | aws package downloaded
  unarchive:
    src: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip
    dest: /opt/
    copy: no

- name: CRONJOB | aws mem metrics
  cron:
    name: aws_mem_metrics
    minute: "*/5"
    hour: "*"
    user: root
    job: "/opt/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --swap-util --swap-used"
    cron_file: aws_mem

- name: CRONJOB | aws disk metrics
  cron:
    name: aws_disk_metrics
    minute: "*/5"
    hour: "*"
    user: root
    job: "/opt/aws-scripts-mon/mon-put-instance-data.pl --disk-path=/ --disk-space-avail --disk-space-used --disk-space-util"
    cron_file: aws_disk
