---

- name: Package | Installation
  yum:
    name:
      - perl-Switch
      - perl-DateTime
      - perl-Sys-Syslog
      - perl-LWP-Protocol-https
      - perl-Digest-SHA
    state: latest

- name: CloudWatch | CloudWatch package
  unarchive:
    src: "{{ aws_cloudwatch_url }}"
    dest: /opt/
    copy: no

- name: CRONJOB MEM | AWS metrics for memory
  cron:
    name: aws_mem_metrics
    minute: "*/5"
    hour: "*"
    user: root
    job: "/opt/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --swap-util --swap-used"
    cron_file: aws_mem

- name: CRONJOB DISK | AWS metrics for disk
  cron:
    name: aws_disk_metrics
    minute: "*/5"
    hour: "*"
    user: root
    job: "/opt/aws-scripts-mon/mon-put-instance-data.pl --disk-path=/ --disk-space-avail --disk-space-used --disk-space-util"
    cron_file: aws_disk
